### ISSUE TITLE
not found: git.io/confd

### ISSUE THREAD

**Issue by aeosynth** [fisherman/z#14]
curl -L git.io/confd >> ~/.config/fish/config.fish

this command fails because git.io/confd is not found

```
$ curl -L git.io/confd
Not Found
```

**Comment by jethrokuan** [comment]
Thanks for reporting this, @bucaran do you mind fixing this? I have no
access a computer for the next two weeks.

In the meantime, you could manually copy the snippet right above that into
config.fish, or upgrade to the beta version of fish (2.3b2).
On 19 May 2016 7:06 pm, "James Campos" <notifications@github.com> wrote:

curl -L git.io/confd >> ~/.config/fish/config.fish

this command fails because is 404

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/fisherman/z/issues/14>

**Comment by jethrokuan** [comment]
This should be resolved now!

**Comment by aeosynth** [comment]
yeah i manually copied the snippet. still gives 404.

**Comment by aeosynth** [comment]
oh, it's resolved because the url was changed in the readme

**Comment by aeosynth** [comment]
the man page needs updating - https://github.com/fisherman/z/blob/master/man/man1/z.1#L50:

    curl \-L git\.io/confd >> ~/\.config/fish/config\.fish

**Comment by jethrokuan** [comment]
Sorry I meant manually copying the lines of code above the snippet into
config.fish.

I'll fix the man page when I get the opportunity.

**Comment by aeosynth** [comment]
@brj man page still shows the old url

**Comment by brj** [comment]
@aeosynth Fixed.

Btw, fish-shell 2.3 is officially out, so no need to use that shim anymore, please upgrade to the latest :)
