### ISSUE TITLE
Allow sub directory matching

### ISSUE THREAD

**Issue by tokozedg** [fisherman/z#27]
Original `z` allows jumping into sub directory. From z man:
`z foo bar     cd to most frecent dir matching foo, then bar`

Adding this feature would be useful.

**Comment by jethrokuan** [comment]
@tokozedg sorry I took a while to reply; was busy organizing a hackathon 😄 

Can I clarify:

1. You want this to match `/foo/...../bar` over `/foo/.../baz`, or:
2. `/.../foo/..` is not found, so it matches `.../bar/..` instead

**Comment by tokozedg** [comment]
Hi,

If I have following  directory structures: `/foo/demo/bar/` and `/something/bar/`
And `/something/bar/` is more frecent than `/foo/demo/bar/`
Than `z foo bar` should move to `/foo/demo/bar` and `z bar` to `/something/bar/`

**Comment by jethrokuan** [comment]
Thanks for your input, I'll take a look at this during my very limited free time. I can't guarantee a fix before summer break.

**Comment by jbucaran** [comment]
@tokozedg 

z foo bar should move to /foo/demo/bar and z bar to /something/bar/

I understand the desired behavior, but what's the current behavior in the above scenario?

**Comment by tokozedg** [comment]
@jethrokuan great thanks.
@jbucaran the second input is ignored, `z` will jump to the dir matching first input.

**Comment by explosic4** [comment]
@tokozedg @jethrokuan Due to the current parsing of arguments, you need to quote the directories when providing multiple dir names.

Belows are the current behavior of z:
`z -l 'foo bar'` 'foo bar' is the argument of option -l
`z -l foo bar` foo is the argument of option -l, bar is the bare argument and is ignored
`z foo bar` foo, bar are both bare argument, but only the first bare argument is used
`z 'foo bar'` 'foo bar' is the first argument, this can move to /foo/demo/bar
`z 'bar foo'` the sequence of bar and foo is ignored, this will also move to /foo/demo/bar, if the rank of /foo/demo/bar if higher than /bar/demo/foo,

**Comment by jethrokuan** [comment]
https://github.com/fisherman/z/pull/41 should resolve this issue immediately, since we're now back in sync with the original z.

**Comment by jethrokuan** [comment]
works on my machine, feel free to reopen if it's still not the case for you.
